### ISSUE TITLE
유저가 쓴 게시글 500

### ISSUE THREAD

**Issue by J1min** [nswon/bssm-task-db#39]
/user/questions 로 요청을 보내면 500이 뜹니다
headers에 토큰은 잘 들어가있어요

**Comment by nswon** [comment]
/user/questions는 없어졌습니다. 대신 /user/{id} 조회시 포함하도록 변경했습니다. https://documenter.getpostman.com/view/18173897/2s8YmLwizb를 참고해주세요!

**Comment by nswon** [comment]
해결되면 close 해주세요 👍

**Comment by J1min** [comment]
감사합니다 답변이 도움이 되었습니다
