### ISSUE TITLE
유저정보 프로필 사진의 root 도메인이 없음

### ISSUE THREAD

**Issue by J1min** [nswon/bssm-task-db#41]
"de1d0432-0d45-4872-b27c-8ac19f701837_THUMBNAIL_60_60_icon_rep_box.gif"

이런식으로만 오고 따로 도메인이 없어요 추가해주세요

**Comment by nswon** [comment]
추가했습니다. 확인해주세요

**Comment by nswon** [comment]
확인하고 close 해주세요오오
