### ISSUE TITLE
highlight.js 활용해서 데이터 post시 500 

### ISSUE THREAD

**Issue by J1min** [nswon/bssm-task-db#61]
아마 글자 수 이슈같습니다 고쳐줘용

**Comment by nswon** [comment]
일단 댓글과 답변 글자 수를 각각 5000자, 10000자로 제한했습니다.

**Comment by J1min** [comment]
일단 알겠습니다. 나중에 가능하시다면 답변 글자 수를 더 늘려주시면 감사하겠습니다.
