### ISSUE TITLE
answers 채택 기능을 구현하고 싶은데 답변 고유ID가 없음

### ISSUE THREAD

**Issue by J1min** [nswon/bssm-task-db#63]
추가좀요

**Comment by J1min** [comment]
그리고 추가로 댓글 부분도 마찬가지임, 삭제 + 수정을 구현하려면 그 고유 아디가 필요!!

**Comment by nswon** [comment]
추가했습니다 확인해주세요.

**Comment by J1min** [comment]
추가된 부분은 확인했지만 백엔드 로직에 이슈가 있는 것 같습니다. 본인의 게시글임에도 400, {"message":"다른 유저입니다."} 라는 메시지가 나옵니다.

**Comment by nswon** [comment]
게시글의 id와 본인 아이디를 알려주시면 확인하겠습니다.

**Comment by J1min** [comment]
본인 아이디 : 1
게시글 아이디 : 1
답변 아이디 : 8

**Comment by nswon** [comment]
수정했습니다

**Comment by J1min** [comment]
잘 됩니다 감사합니다. 혹시 가능하시다면 채택된 답변을 API 답변 배열에서 최상단으로 배치해주시고 그 아래 답변들은 좋아요 순으로 정렬해주실수 있으실까요?

**Comment by nswon** [comment]
#64 이슈를 해결하고 적용하겠습니다

**Comment by J1min** [comment]
넹 귀찮아서 새 이슈 안터트렸는데 죄송합니다 담부턴 이슈 하나하나 터트릴게요
