### ISSUE TITLE
한 게시글에 채택이 여러개 되는 버그 

### ISSUE THREAD

**Issue by J1min** [nswon/bssm-task-db#66]
2번 게시글을 보시면 한 게시글에 채택이 2개가 되어있습니다. 
프론트엔드에서 일단 작성자가 한번 채택하면 그 이후에 채택 버튼이 보이지 않도록 처리했으나, 백엔드 로직도 처리가 필요해보입니다.

**Comment by nswon** [comment]
나중에 수정하겠습니다
