### ISSUE TITLE
좋아요 0에서 싫어요시 좋아요가 -1 이 아니고 0이 됨

### ISSUE THREAD

**Issue by J1min** [nswon/bssm-task-db#74]
6번 게시물입니다 확인 부탁드립니다.

**Comment by nswon** [comment]
잘 됩니다. 아마도 제가 테스트할 때 202110102계정으로 해서 이미 좋아요가 되어있는 상태에서 싫어요를 누르신 것 같습니다.

**Comment by J1min** [comment]
감사합니당
